development: &development
  adapter      : postgresql
  encoding     : unicode
  database     : <%= ENV['APP_NAME'] %>_development
  template     : template0
  pool         : 5
  min_messages : warning

test: &test
  <<: *development
  database     : <%= ENV['APP_NAME'] %>_test

staging: &staging
  <<: *development
  database     : <%= ENV['APP_NAME'] %>_staging

production: &production
  <<: *development
  database     : <%= ENV['APP_NAME'] %>_production
