development: &development
  adapter      : postgresql
  encoding     : unicode
  database     : my_app_development
  template     : template0
  pool         : 5
  min_messages : warning

test: &test
  <<: *development
  database     : my_app_test

staging: &staging
  <<: *development
  database     : my_app_staging

production: &production
  <<: *development
  database     : my_app_production
